---

- name: Ensure homebrew directory ownership
  file: path={{ homebrew_dir }} owner={{ homebrew_user }} group={{ homebrew_group }} mode=0755 state=directory
  tags:
    - homebrew
- name: Clone homebrew
  git: repo={{ homebrew_repo }} dest={{ homebrew_dir }} update=no
  become: true
  become_user: "{{ homebrew_user }}"
  tags:
    - homebrew
- name: Tap additional Homebrew formulae repositories
  homebrew_tap: tap={{ item }} state=present
  become: true
  become_user: "{{ homebrew_user }}"
  with_items: "{{ homebrew_taps }}"
  tags:
    - homebrew
- name: Set Homebrew facts
  set_fact:
    ansible_pkg_mgr: "homebrew"
    homebrew_bin: "{{ homebrew_dir }}/bin/brew"
  tags:
    - homebrew
