---
- name: Remove installer keep file
  file:
    path: /usr/local/.com.apple.installer.keep
    state: absent
- name: Check if homebrew is installed
  stat: path=/usr/local/bin/brew
  register: check_homebrew_installed
  tags:
    - homebrew
- name: Clone homebrew
  git: repo={{ homebrew_repo }} dest={{ homebrew_dir }} update=no
  when: not check_homebrew_installed.stat.exists
  tags:
    - homebrew
- name: Fix homebrew permissions
  shell: chown -R {{ homebrew_user }}:{{ homebrew_group }} /usr/local/*
  when: not check_homebrew_installed.stat.exists
  tags:
    - homebrew
- name: Create additional directories
  file:
    path: "/usr/local/{{ item }}"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    state: directory
  with_items:
    - var
  tags:
    - homebrew
- name: Tap additional Homebrew formulae repositories
  homebrew_tap: tap={{ item }} state=present
  become: true
  become_user: "{{ homebrew_user }}"
  with_items: "{{ homebrew_taps }}"
  tags:
    - homebrew
- name: Set Homebrew facts
  set_fact:
    ansible_pkg_mgr: "homebrew"
    homebrew_bin: "{{ homebrew_dir }}/bin/brew"
  tags:
    - homebrew
